app:
  port: 9966


postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  
redis:
  host: localhost
  port: 6379

starter:
  host: http://localhost:9966
